version = 0.1

[default]
[default.global.parameters]
stack_name = "personal-job-dashboard"

[default.build.parameters]
cached = true
parallel = true

[default.sync.parameters]
watch = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"

[default.package.parameters]
resolve_s3 = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

